### ISSUE TITLE
Inconsistent use of terms in requirements

### ISSUE THREAD

**Issue by MaiNorapong** [nuttapol-kor/ku-polls#1]
> 4.&nbsp;Users have the number of survey items and the number of responses unrestricted.

As Mr James has posted in the classroom this morning, use "poll" instead of "survey" for now.

Saying the number of responses is unrestricted might make some misunderstand that one "user" can vote more than once, which shouldn't be the case. Perhaps adding a clause like "but they are limited to one vote for each poll" for clarity would be good.

> 1.&nbsp;Users can view a list of the available polls.

> 7.&nbsp;Web visitors cannot see the question before the opening date.

If "the question" and "polls" refer to the same thing, using the same term again would make it more clear.

> 3.&nbsp;Users can view and edit previously submitted polls before the end date.

Writing it this way would make it seem like the poll, that is the question and the choices, are editable until the "end date". If by this you actually meant the choice voted for can be changed, using these words instead would make it clearer.

**Comment by nuttapol-kor** [comment]
Thank you.
